config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/sign_up', to: 'static_pages#sign_up'
  get '/login', to: 'static_pages#login'

  resources :billboards do
  	resources :artists
  end
  resources :artists do
  	resources :songs
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
	has_many :songs, dependent: :destroy
	belongs_to :billboard
end

app/models/billboard.rb
class Billboard < ApplicationRecord
	has_many :artists
end

app/models/song.rb
class Song < ApplicationRecord
	belongs_to :artist, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_billboard
  before_action :set_artist, except: [:index, :new, :create]

  def index
  	@artists = @billboard.artists
  end

  def show
  end

  def new
  	@artist = @billboard.artists.new
  end

  def edit
  end

  def create
    @artist = @billboard.artists.new(artist_params)
    if @artist.save
      redirect_to billboard_artist_path(@billboard, @artist)
    else
      render :new
    end
  end


	def update
	  if @artist.update(artist_params)
	    redirect_to billboard_artist_path(@billboard, @artist)
	  else
	    render :edit
	  end
	end

	def destroy
	  @artist.destroy
	  redirect_to artists_path(@billboard)
	end

  private
    def artist_params
      params.require(:artist).permit(:name, :genre,
                                    :rating, :bio)
    end

    def set_billboard
      @billboard = Billboard.find(params[:billboard_id])
    end

    def set_artist
      @artist = @billboard.artists.find(params[:id])
    end
end

app/controllers/billboards_controller.rb
class BillboardsController < ApplicationController
  before_action :set_billboard, except: [:index, :new, :create]

  def index
  	@billboards = Billboard.all
  end

  def show
  end

  def new
  	@billboard = Billboard.new
  end

  def edit
  end

  def update
  	if @billboard.update(billboard_params)
  		redirect_to billboard_path(@billboard)
  	else
  		render.new
  	end
  end

  def create
  	@billboard = Billboard.new(billboard_params)
  	if @billboard.save
  		redirect_to billboard_path(@billboard)
  	else
  		render :new
  	end
  end

  def destroy
  	@billboard.destroy
  	redirect_to billboards_path
  end

  private
  	def billboard_params
  		params.require(:billboard).permit(:name, :total)
  	end

  	def set_billboard
			@billboard = Billboard.find(params[:id])
  	end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_artist
  before_action :set_song, except: [:index, :new, :create]

  def index
  	@songs = @artist.songs
  end

  def show
  end

  def new
  	@song = @artist.songs.new
  end

  def edit
  end

  def create
    @song = @artist.songs.new(song_params)
    if @song.save
      redirect_to artist_song_path(@artist, @song)
    else
      render :new
    end
  end


	def update
	  if @song.update(song_params)
	    redirect_to artist_song_path(@artist, @song)
	  else
	    render :edit
	  end
	end

	def destroy
	  @song.destroy
	  redirect_to billboard_artist_path(@artist)
	end

  private
    def song_params
      params.require(:song).permit(:title, :album,
                                    :release_date)
    end

    def set_artist
      @artist = Artist.find(params[:artist_id])
    end

    def set_song
      @song = @artist.songs.find(params[:id])
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def sign_up
  end

  def login
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/billboards_helper.rb
module BillboardsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/views/artists/edit.html.erb
<h1>Edit artist</h1>
<div class="container">
  <div class="row">
    <%= form_for [@billboard, @artist] do |f| %>
      <div class="col m6">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
      <div class="col m6">
        <%= f.label :genre %>
        <%= f.text_field :genre %>
      </div>
      <div class="col m6">
        <%= f.label :rating %>
        <%= f.number_field :rating, min: 0, max: 10 %>
      </div>
      <div class="col m6">
        <%= f.label :bio %>
        <%= f.text_area :bio %>
      </div>
      <%= f.submit class: "btn black white-text" %>
    <% end %>
  </div>
</div>

app/views/artists/index.html.erb
<h1 class="center blue-text text-accent-4">The artist list</h1>
<div class="center">
<%= link_to 'Add Artist', new_billboard_artist_path, class: "btn green white-text" %>
</div>
<hr />
<ul class="collection">
	<% @artists.each do |artist| %>
		<li class="collection-item">
			<%= link_to artist.name, billboard_artist_path(@billboard, artist) %>
		</li>
	<% end %>
</ul>

app/views/artists/new.html.erb
<h1>Add an artist</h1>
<div class="container">
  <div class="row">
    <%= form_for [@billboard, @artist] do |f| %>
      <div class="col m6">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
      <div class="col m6">
        <%= f.label :genre %>
        <%= f.text_field :genre %>
      </div>
      <div class="col m6">
        <%= f.label :rating %>
        <%= f.number_field :rating, min: 0, max: 10 %>
      </div>
      <div class="col m6">
        <%= f.label :bio %>
        <%= f.text_area :bio %>
      </div>
      <%= f.submit class: "btn black white-text" %>
    <% end %>
  </div>
</div>

app/views/artists/show.html.erb
<h1 class='center green-text text-darken-2'>Artist</h1>
	<div class="right">
		<h3><%= @artist.name %></h3>
		<h3><%= @artist.genre %></h3>
		<h3><%= @artist.rating %></h3>
		<h3><%= @artist.bio %></h3>
	</div>
			<div class="btn-large yellow">
				<%= link_to 'Edit', edit_billboard_artist_path(@billboard, @artist)%>
			</div>
			<div class="btn-large red">
				<%= link_to 'Delete', artists_path(@artist), method: :delete, data: {confirm: 'You sure'} %>
			</div>
			<div class="btn-large orange">
				<%= link_to 'Add Song', artist_songs_path(@artist, @song) %>
			</div>

app/views/billboards/edit.html.erb
<h1>Edit it up</h1>
<div class="container">
  <div class="row">
    <%= form_for @billboard do |f| %>
      <div class="col m6">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
      <div class="col m6">
        <%= f.label :total %>
        <%= f.number_field :total, min: 0, max: 25 %>
      </div>
      <%= f.submit class: "btn black white-text" %>
    <% end %>
  </div>
</div>

app/views/billboards/index.html.erb
<h1 class="center blue-text text-accent-4">Your center for top lists and such</h1>
<div class="center">
<%= link_to 'Add Billboard', new_billboard_path, class: "btn green white-text" %>
</div>
<hr />
<ul class="collection">
	<% @billboards.each do |billboard| %>
		<li class="collection-item">
			<%= link_to billboard.name, billboard_path(billboard) %>
		</li>
	<% end %>
</ul>

app/views/billboards/new.html.erb
<h1>Make a Billboard</h1>
<div class="container">
  <div class="row">
    <%= form_for @billboard do |f| %>
      <div class="col m6">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
      <div class="col m6">
        <%= f.label :total %>
        <%= f.number_field :total, min: 0, max: 25 %>
      </div>
      <%= f.submit class: "btn black white-text" %>
    <% end %>
  </div>
</div>

app/views/billboards/show.html.erb
<h1 class='center green-text text-darken-2'>This is your Billboard</h1>
	<div class="right">
		<h3><%= @billboard.name %>
				<%= @billboard.total %>
			</h3>
	</div>
			<div class="btn-large yellow">
				<%= link_to 'Edit', edit_billboard_path(@billboard)%>
			</div>
			<div class="btn-large red">
			<%= link_to 'Delete', billboard_path(@billboard), method: :delete, data: {confirm: 'You sure'} %>
			</div>
			<div class="btn-large orange">
			<%= link_to 'Add/See Artists', billboard_artists_path(@billboard, @artist) %>
			</div>
		

app/views/layouts/_navbar.html.erb
<nav class="blue">
	   <ul class="left">
		    <li><a href="/">Home</a></li>
		    <li><a href="/help">Help</a></li>
		    <li><a href="/sign_up">Sign Up</a></li>
		    <li><a href="/login">Login</a></li>
	   </ul>
	   <ul class="right">
	   		<li><a href="/billboards">Billboards</a></li>
	   </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BillboardRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  

  <body class="container">
  	<%= render 'layouts/navbar' %>
    <img class="responsive-img" src="album-covers.png" />
    <%= yield %>
  </body>
</html>

app/views/songs/edit.html.erb
<h1>Songs#edit</h1>
<p>Find me in app/views/songs/edit.html.erb</p>

app/views/songs/index.html.erb
<h1 class="center blue-text text-accent-4">The song list</h1>
<div class="center">
<%= link_to 'Add Song', new_artist_song_path, class: "btn green white-text" %>
</div>
<hr />
<ul class="collection">
	<% @songs.each do |song| %>
		<li class="collection-item">
			<%= link_to song.title, artist_song_path(@artist, song) %>
		</li>
	<% end %>
</ul>

app/views/songs/new.html.erb
<h1>Add an song</h1>
<div class="container">
  <div class="row">
    <%= form_for [@artist, @song] do |f| %>
      <div class="col m6">
        <%= f.label :title %>
        <%= f.text_field :title %>
      </div>
      <div class="col m6">
        <%= f.label :album %>
        <%= f.text_field :album %>
      </div>
      <div class="col m6">
        <%= f.label :release_date %>
        <%= f.date_field(:release_date) %>
      </div>
      <%= f.submit class: "btn black white-text" %>
    <% end %>
  </div>
</div>

app/views/songs/show.html.erb
<h1 class='center green-text text-darken-2'>Song</h1>
	<div class="right">
		<h3><%= @song.title %></h3>
		<h3><%= @song.album %></h3>
		<h3><%= @song.release_date %></h3>
		</div>
			<%= link_to 'Edit', edit_artist_song_path(@artist, @song)%>
			<%= link_to 'Delete', artist_song_path(@artist, @song), method: :delete, data: {confirm: 'You sure'} %>

app/views/static_pages/help.html.erb
<h1 class="center green-text">Help Page</h1>
<p>If you want some help ask a friendly old person if they can help you figure out this darn web application. If they can't figure it out maybe the police can help. That is just a though</p>
<p class="center">Find a link <a href="http://www.wikihow.com/Listen-to-Music">Here</a></p>

app/views/static_pages/home.html.erb
<h1 class="center green-text">Welcome to you source for music</h1>
<p class="center">Find 1,000,000,000,000,000 songs here</p>

app/views/static_pages/login.html.erb
<h1>StaticPage#login</h1>
<p>Find me in app/views/static_page/login.html.erb</p>

app/views/static_pages/sign_up.html.erb
<h1>StaticPage#sign_up</h1>
<p>Find me in app/views/static_page/sign_up.html.erb</p>